version: "3"

services:
  my-dashboard:
    container_name: my-dashboard
    build:
      context: ./my-dashboard
      dockerfile: dev.Dockerfile

    # Set environment variables directly in the docker-compose file
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
      CHOKIDAR_USEPOLLING: "true"
      NEXT_WEBPACK_USEPOLLING: 1

    # Set environment variables based on the .env file
    env_file:
      - .env
    volumes:            
      - ./my-dashboard/public:/app/public    
      - ./my-dashboard/src:/app/src
      - ./my-dashboard/package.json:/app/package.json
      - ./my-dashboard/package-lock.json:/app/package-lock.json

    restart: always
    ports:
      - 3000:3000
    networks:
      - my_network
    
    

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  my_network:
    external: true
